sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev

before_script:
  - docker build -t maxmilton/travis .

script:
  - docker run -v $(pwd):/project --rm maxmilton/travis version
