sudo: required

services:
  - docker

before_script:
  - docker build -t maxmilton/travis .

script:
  - docker run -v $(pwd):/project --rm maxmilton/travis version

# TODO: Automatically trigger a new image on Docker hub or revoke image if failed
